import CoreML
import CoreVideo
import Foundation
import Masking
import Vision
import YOLODecoding

/// Runs the exported YOLO segmentation model and decodes its output.
final class YOLOSegmenter: PavementSegmenter {

    enum SegmenterError: Error {
        case modelNotFound
        case unexpectedOutputs
        case unsupportedTensorType
    }

    private let model: VNCoreMLModel
    private let decoder: YOLOMaskDecoder

    init(modelName: String = "train11-yolov8n-seg-640",
         decoder: YOLOMaskDecoder = YOLOMaskDecoder()) throws {
        guard let url = Bundle.main.url(forResource: modelName, withExtension: "mlmodelc") else {
            throw SegmenterError.modelNotFound
        }
        let configuration = MLModelConfiguration()
        configuration.computeUnits = .all
        self.model = try VNCoreMLModel(for: MLModel(contentsOf: url, configuration: configuration))
        self.decoder = decoder
    }

    func mask(from frame: CVPixelBuffer) throws -> Mask? {
        let request = VNCoreMLRequest(model: model)
        // Letterbox rather than stretch. Squashing a portrait frame into the
        // square input distorts it far beyond anything in the training set:
        // measured on recorded frames, the same scene scores 0.008 stretched
        // and 0.845 letterboxed.
        request.imageCropAndScaleOption = .scaleFit

        try VNImageRequestHandler(cvPixelBuffer: frame, orientation: .up).perform([request])

        guard let observations = request.results as? [VNCoreMLFeatureValueObservation] else {
            throw SegmenterError.unexpectedOutputs
        }

        let arrays = observations.compactMap(\.featureValue.multiArrayValue)

        // Bind by shape. Output names are generated by the converter and change
        // between exports.
        guard let detections = arrays.first(where: { $0.shape.count == 3 }),
              let prototypes = arrays.first(where: { $0.shape.count == 4 }) else {
            throw SegmenterError.unexpectedOutputs
        }

        guard let mask = decoder.decode(
            detections: try floats(from: detections),
            rows: detections.shape[1].intValue,
            columns: detections.shape[2].intValue,
            prototypes: try floats(from: prototypes)
        ) else {
            return nil
        }

        // Discard the letterbox padding, so the mask lines up with the frame
        // rather than with the model's square input.
        let geometry = LetterboxGeometry(
            sourceWidth: CVPixelBufferGetWidth(frame),
            sourceHeight: CVPixelBufferGetHeight(frame),
            inputSize: decoder.configuration.inputSize,
            maskSize: decoder.configuration.prototypeSize
        )
        return mask.cropped(to: geometry.contentRect)
    }

    private func floats(from array: MLMultiArray) throws -> [Float] {
        guard array.dataType == .float32 else {
            throw SegmenterError.unsupportedTensorType
        }
        return array.withUnsafeBufferPointer(ofType: Float.self) { Array($0) }
    }
}
